# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='genes',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('ids', models.CharField(max_length=34)),
                ('gene', models.CharField(max_length=34)),
                ('gen_sco', models.CharField(max_length=34)),
            ],
        ),
        migrations.CreateModel(
            name='messa',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('ids', models.CharField(max_length=34)),
                ('loca', models.CharField(max_length=34)),
                ('alias', models.CharField(default='', max_length=100)),
                ('dise', models.CharField(max_length=20)),
                ('dis_sco', models.CharField(max_length=20)),
                ('snp', models.CharField(max_length=34)),
            ],
        ),
        migrations.CreateModel(
            name='sequ',
            fields=[
                ('ids', models.CharField(max_length=34, primary_key=True, serialize=False)),
                ('locas', models.CharField(default='chr', max_length=34)),
                ('expre', models.CharField(max_length=34)),
                ('seq', models.TextField()),
            ],
        ),
    ]
