# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='seqe',
            fields=[
                ('ids', models.CharField(max_length=34, primary_key=True, serialize=False)),
                ('locas', models.CharField(default='chr', max_length=34)),
                ('expre', models.CharField(max_length=34)),
                ('seq', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='sequ',
        ),
    ]
