# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0002_auto_20170512_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messa',
            name='dise',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='messa',
            name='snp',
            field=models.CharField(max_length=120),
        ),
    ]
