# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0003_auto_20170516_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='messa',
            name='snpid',
            field=models.CharField(default='1', max_length=34),
        ),
        migrations.AddField(
            model_name='seqe',
            name='classs',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='seqe',
            name='exons',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='seqe',
            name='length',
            field=models.CharField(default='1', max_length=5),
        ),
        migrations.AddField(
            model_name='seqe',
            name='strand',
            field=models.CharField(default='+', max_length=3),
        ),
    ]
