# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.CharField(max_length=9)),
                ('loca', models.CharField(max_length=34)),
                ('seq', models.CharField(max_length=34)),
                ('snp', models.CharField(max_length=32)),
                ('dise', models.CharField(max_length=20)),
                ('dis_sco', models.IntegerField(max_length=2)),
                ('gene', models.CharField(max_length=34)),
                ('gen_sco', models.IntegerField(max_length=2)),
                ('expre', models.IntegerField(max_length=2)),
            ],
        ),
    ]
