# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='dis_sco',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='expre',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='gen_sco',
            field=models.IntegerField(),
        ),
    ]
